from __future__ import annotations

import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def _read(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


class UiSavedDecksRegressionTests(unittest.TestCase):
    def test_workspace_declares_saved_deck_storage_and_state(self) -> None:
        source = _read("ui_harness/src/views/WorkspaceView.tsx")
        self.assertIn('const SAVED_DECKS_STORAGE_KEY = "mtg_saved_decks_v1";', source)
        self.assertIn('const SELECTED_SAVED_DECK_STORAGE_KEY = "mtg_selected_saved_deck_v1";', source)
        self.assertIn('type SavedDeckDialogMode = "SAVE" | "RENAME" | "DELETE";', source)
        self.assertIn("function normalizeSavedDeckEntries(value: unknown): SavedDeckEntry[] {", source)
        self.assertIn("const dedupedByKey = new Map<string, SavedDeckEntry>();", source)
        self.assertIn("const key = normalized.name.toLowerCase();", source)
        self.assertIn("const [savedDecks, setSavedDecks] = useState<SavedDeckEntry[]>(() => {", source)
        self.assertIn("const [savedDeckDialogMode, setSavedDeckDialogMode] = useState<SavedDeckDialogMode | null>(null);", source)
        self.assertIn("const [savedDeckDialogTargetName, setSavedDeckDialogTargetName] = useState(\"\");", source)
        self.assertIn("const [savedDeckDialogNameInput, setSavedDeckDialogNameInput] = useState(\"\");", source)
        self.assertIn("const savedDeckDialogDescriptionId = useId();", source)
        self.assertIn("const savedDeckDialogValidationId = useId();", source)
        self.assertIn("const savedDeckDialogRestoreFocusRef = useRef<HTMLElement | null>(null);", source)
        self.assertIn("const savedDeckDialogShellRef = useRef<HTMLDivElement | null>(null);", source)
        self.assertIn("window.localStorage.getItem(SAVED_DECKS_STORAGE_KEY)", source)
        self.assertIn("return normalizeSavedDeckEntries(parsed);", source)
        self.assertIn("window.localStorage.setItem(SAVED_DECKS_STORAGE_KEY, JSON.stringify(savedDecks))", source)
        self.assertIn("window.localStorage.getItem(SELECTED_SAVED_DECK_STORAGE_KEY)", source)
        self.assertIn("window.localStorage.setItem(SELECTED_SAVED_DECK_STORAGE_KEY, normalizedSelection)", source)
        self.assertIn("window.localStorage.removeItem(SELECTED_SAVED_DECK_STORAGE_KEY)", source)

    def test_workspace_has_save_and_open_handlers(self) -> None:
        source = _read("ui_harness/src/views/WorkspaceView.tsx")
        self.assertIn("function closeSavedDeckDialog(): void", source)
        self.assertIn("function saveDeckByName(deckNameRaw: string): boolean", source)
        self.assertIn("function renameSavedDeckByName(deckNameRaw: string, nextDeckNameRaw: string): boolean", source)
        self.assertIn("function deleteSavedDeckByName(deckNameRaw: string): boolean", source)
        self.assertIn("function handleSubmitSavedDeckDialog(): void", source)
        self.assertIn("function handleSaveDeck(): void", source)
        self.assertIn("function handleLoadSavedDeck(deckNameRaw: string): void", source)
        self.assertIn("function handleRenameSavedDeck(deckNameRaw: string): void", source)
        self.assertIn("function handleDeleteSavedDeck(deckNameRaw: string): void", source)
        self.assertIn("setSavedDecks((previous: SavedDeckEntry[]) => {", source)
        self.assertIn("setSelectedSavedDeckName(savedDeck.name);", source)
        self.assertIn('setToastMessage(`Opened deck "${savedDeck.name}".`);', source)
        self.assertIn('setToastMessage(`Renamed deck "${existingDeck.name}" to "${renamedDeckName}".`);', source)
        self.assertIn('setToastMessage(`Deleted deck "${existingDeck.name}".`);', source)
        self.assertIn("if (!existingDeck && savedDecks.length >= SAVED_DECKS_MAX) {", source)
        self.assertIn('setToastMessage(`Saved deck limit (${SAVED_DECKS_MAX}) reached. Delete a saved deck before creating a new one.`);', source)
        self.assertNotIn("window.prompt(", source)
        self.assertNotIn("window.confirm(", source)

    def test_workspace_renders_saved_deck_modal_flow(self) -> None:
        source = _read("ui_harness/src/views/WorkspaceView.tsx")
        self.assertIn('{savedDeckDialogMode ? (', source)
        self.assertIn('className="card-modal-shell smart-tools-modal-shell workspace-saved-deck-modal-shell"', source)
        self.assertIn('aria-label={', source)
        self.assertIn('className="workspace-saved-deck-modal-form"', source)
        self.assertIn('className="workspace-saved-deck-modal-target"', source)
        self.assertIn('className="workspace-action-row workspace-saved-deck-modal-actions"', source)
        self.assertIn('className="workspace-link-button workspace-saved-deck-modal-submit"', source)
        self.assertIn("const savedDeckDialogAtCapacity = useMemo(() => {", source)
        self.assertIn("const savedDeckDialogRenameConflict = useMemo(() => {", source)
        self.assertIn("const savedDeckDialogValidationMessage = useMemo(() => {", source)
        self.assertIn("if (savedDeckDialogAtCapacity) {", source)
        self.assertIn("Saved deck limit (${SAVED_DECKS_MAX}) reached. Delete a saved deck before creating a new one.", source)
        self.assertIn("const savedDeckDialogDescribedBy = useMemo(() => {", source)
        self.assertIn('if (event.key === "Escape") {', source)
        self.assertIn('if (event.key !== "Tab") {', source)
        self.assertIn("const tabOrderedElements = resolveFocusableElements();", source)
        self.assertIn('const preferredFocusTarget =', source)
        self.assertIn('savedDeckDialogMode === "DELETE"', source)
        self.assertIn("[data-saved-deck-submit=\"true\"]", source)
        self.assertIn("[data-saved-deck-name-input=\"true\"]", source)
        self.assertIn('window.addEventListener("keydown", handleKeyDown);', source)
        self.assertIn("function captureSavedDeckDialogFocusOrigin(): void", source)
        self.assertIn("captureSavedDeckDialogFocusOrigin();", source)
        self.assertIn("savedDeckDialogRestoreFocusRef.current = activeElement instanceof HTMLElement ? activeElement : null;", source)
        self.assertIn("const focusTarget = savedDeckDialogRestoreFocusRef.current;", source)
        self.assertIn("focusTarget.focus();", source)
        self.assertIn("ref={savedDeckDialogShellRef}", source)
        self.assertIn("aria-describedby={savedDeckDialogDescribedBy}", source)
        self.assertIn("id={savedDeckDialogDescriptionId}", source)
        self.assertIn('className="workspace-saved-deck-modal-validation"', source)
        self.assertIn("aria-invalid={savedDeckDialogValidationMessage !== \"\"}", source)
        self.assertIn("aria-describedby={savedDeckDialogValidationMessage !== \"\" ? savedDeckDialogValidationId : undefined}", source)
        self.assertIn('data-saved-deck-name-input="true"', source)
        self.assertIn('data-saved-deck-submit="true"', source)
        self.assertIn("tabIndex={-1}", source)
        self.assertIn('setSavedDeckDialogMode("SAVE");', source)
        self.assertIn('setSavedDeckDialogMode("RENAME");', source)
        self.assertIn('setSavedDeckDialogMode("DELETE");', source)

    def test_workspace_wires_saved_decks_into_deck_editor_panel(self) -> None:
        source = _read("ui_harness/src/views/WorkspaceView.tsx")
        self.assertIn("savedDeckNames={savedDeckNames}", source)
        self.assertIn("selectedSavedDeckName={selectedSavedDeckName}", source)
        self.assertIn("function handleSelectedSavedDeckNameChange(deckNameRaw: string): void", source)
        self.assertIn("onSelectedSavedDeckNameChange={handleSelectedSavedDeckNameChange}", source)
        self.assertIn("onSaveDeck={handleSaveDeck}", source)
        self.assertIn("onLoadSavedDeck={handleLoadSavedDeck}", source)
        self.assertIn("onRenameSavedDeck={handleRenameSavedDeck}", source)
        self.assertIn("onDeleteSavedDeck={handleDeleteSavedDeck}", source)

    def test_deck_editor_renders_saved_deck_controls(self) -> None:
        source = _read("ui_harness/src/components/deck/DeckEditorPanel.tsx")
        self.assertIn("savedDeckNames?: string[];", source)
        self.assertIn("onRenameSavedDeck?: (deckName: string) => void;", source)
        self.assertIn("onDeleteSavedDeck?: (deckName: string) => void;", source)
        self.assertIn("const savedDeckStatusId = useId();", source)
        self.assertIn("const canRenameSavedDeck = hasMatchingSavedDeck && Boolean(onRenameSavedDeck);", source)
        self.assertIn("const canDeleteSavedDeck = hasMatchingSavedDeck && Boolean(onDeleteSavedDeck);", source)
        self.assertIn("const hasMissingSavedDeckSelection = normalizedSavedDeckName !== \"\" && !hasMatchingSavedDeck;", source)
        self.assertIn("const canSelectSavedDeck = hasSavedDeckOptions || hasMissingSavedDeckSelection;", source)
        self.assertIn("const savedDeckStatusMessage = useMemo(() => {", source)
        self.assertIn("const savedDeckSelectValue = useMemo(() => {", source)
        self.assertIn("is no longer available. Select another saved deck or clear the selection.", source)
        self.assertIn('className="deck-editor-saved-actions-group"', source)
        self.assertIn('className="deck-editor-saved-actions"', source)
        self.assertIn("aria-describedby={savedDeckStatusId}", source)
        self.assertIn("aria-invalid={hasMissingSavedDeckSelection}", source)
        self.assertIn("aria-errormessage={hasMissingSavedDeckSelection ? savedDeckStatusId : undefined}", source)
        self.assertIn("value={savedDeckSelectValue}", source)
        self.assertIn('deck-editor-saved-select-warning', source)
        self.assertIn("disabled={!canSelectSavedDeck}", source)
        self.assertIn("[Missing] {normalizedSavedDeckName}", source)
        self.assertIn('className="deck-editor-clear-selection-button"', source)
        self.assertIn('onSelectedSavedDeckNameChange("");', source)
        self.assertIn("deck-editor-saved-status-warning", source)
        self.assertIn('aria-atomic="true"', source)
        self.assertIn("Save Deck", source)
        self.assertIn("deck-editor-saved-select", source)
        self.assertIn("Saved decks...", source)
        self.assertIn("Open", source)
        self.assertIn("Rename", source)
        self.assertIn("Delete", source)

    def test_saved_deck_controls_and_layout_are_styled(self) -> None:
        source = _read("ui_harness/src/styles.css")
        self.assertIn(".deck-editor-saved-actions {", source)
        self.assertIn(".deck-editor-saved-actions-group {", source)
        self.assertIn(".deck-editor-saved-status {", source)
        self.assertIn(".deck-editor-saved-status-warning {", source)
        self.assertIn(".deck-editor-saved-select-wrap {", source)
        self.assertIn(".deck-editor-saved-select {", source)
        self.assertIn(".deck-editor-saved-select-warning {", source)
        self.assertIn(".deck-editor-saved-select-warning:focus-visible {", source)
        self.assertIn(".deck-editor-save-button,", source)
        self.assertIn(".deck-editor-open-button,", source)
        self.assertIn(".deck-editor-rename-button,", source)
        self.assertIn(".deck-editor-delete-button,", source)
        self.assertIn(".deck-editor-clear-selection-button,", source)
        self.assertIn(".deck-editor-clear-selection-button {", source)
        self.assertIn(".deck-editor-clear-selection-button:hover {", source)
        self.assertIn("@media (max-width: 640px) {", source)
        self.assertIn(".deck-editor-saved-actions .deck-editor-save-button,", source)
        self.assertIn(".deck-editor-saved-actions .deck-editor-clear-selection-button {", source)
        self.assertIn(".workspace-saved-deck-modal-shell {", source)
        self.assertIn(".workspace-saved-deck-modal-form {", source)
        self.assertIn(".workspace-saved-deck-modal-validation {", source)
        self.assertIn(".workspace-saved-deck-modal-actions .workspace-link-button {", source)
        self.assertIn(".workspace-saved-deck-modal-target {", source)
        self.assertIn(".workspace-saved-deck-modal-actions {", source)
        self.assertIn(".workspace-saved-deck-modal-submit {", source)
        self.assertIn(".deck-editor-board {", source)
        self.assertIn("grid-template-columns: repeat(3, minmax(0, 1fr));", source)


if __name__ == "__main__":
    unittest.main()
