from __future__ import annotations


COUNTERFACTUAL_STRESS_PRIMITIVES_V1_VERSION = "counterfactual_stress_primitives_v1"

# Closed-world primitive IDs used by counterfactual stress scenarios.
# Keep source-controlled and deterministic.
COUNTERFACTUAL_GRAVEYARD_RELIANCE_PRIMITIVE_IDS = [
    "ARTIFACT_RECURSION",
    "CAST_FROM_GRAVEYARD",
    "REANIMATION_TO_BATTLEFIELD",
    "RECURSION_TO_HAND",
    "SELF_MILL",
    "SPELL_RECURSION_INSTANT_SORC",
    "TUTOR_TO_GRAVEYARD",
]

COUNTERFACTUAL_ARTIFACT_RELIANCE_PRIMITIVE_ID = "MANA_RAMP_ARTIFACT_ROCK"
COUNTERFACTUAL_ENCHANTMENT_RELIANCE_PRIMITIVE_ID = "ENCHANTMENT_CAST_PAYOFF"
